[workspace]
name = "teleop_xr_ros2_example"
version = "0.1.0"
authors = ["Antigravity <antigravity@google.com>"]
channels = ["robostack-humble", "conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
uv = "*"
ros-humble-desktop = "*"
colcon-common-extensions = "*"
vcstool = "*"
rosdep = "*"
ninja = "*"
cmake = "*"
c-compiler = "*"
cxx-compiler = "*"
ros-humble-moveit-resources-panda-moveit-config = "*"
ros-humble-moveit-ros-move-group = "*"
ros-humble-moveit-configs-utils = "*"
ros-humble-moveit-planners-ompl = "*"
ros-humble-moveit-ros-visualization = "*"
ros-humble-controller-manager = "*"
ros-humble-joint-state-broadcaster = "*"
ros-humble-joint-trajectory-controller = "*"
ros-humble-position-controllers = "*"
ros-humble-ros2controlcli = "*"
ros-humble-gripper-controllers = "*"
ros-humble-moveit-simple-controller-manager = "*"
ros-humble-xacro = "*"

[pypi-dependencies]
teleop-xr = { git = "https://github.com/qrafty-ai/teleop_xr.git", rev="v1.2.0" }
pyroki = { git = "https://github.com/chungmin99/pyroki.git" }
yourdfpy = "*"
jaxlie = "*"
jax = "*"
jaxlib = "*"
jaxls = "*"
typing_extensions = "*"
filelock = "*"

[tasks]
setup = "bash scripts/setup.sh"
build = "colcon build --symlink-install"
test = "colcon test"
demo = "bash -c 'source install/setup.bash && ros2 launch teleop_xr_ros2_example demo.launch.py'"
