[workspace]
name = "modern-ros2-workspace"
version = "0.1.0"
authors = ["Antigravity <antigravity@google.com>"]
channels = ["robostack-humble", "conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
uv = "*"
ros-humble-desktop = "*"
colcon-common-extensions = "*"
vcstool = "*"
rosdep = "*"
ninja = "*"
cmake = "*"
c-compiler = "*"
cxx-compiler = "*"

[tasks]
setup = "bash scripts/setup.sh"
build = "colcon build --symlink-install"
test = "colcon test"
